drop policy "Enable insert for anon role" on "public"."user_infos";

create table "public"."user_sessions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "telemetry" jsonb
);


alter table "public"."user_sessions" enable row level security;

CREATE UNIQUE INDEX user_sessions_pkey ON public.user_sessions USING btree (id);

alter table "public"."user_sessions" add constraint "user_sessions_pkey" PRIMARY KEY using index "user_sessions_pkey";

alter table "public"."user_sessions" add constraint "user_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_sessions" validate constraint "user_sessions_user_id_fkey";

create policy "Enable read access for all users"
on "public"."user_infos"
as permissive
for insert
to public
with check (true);


create policy "Enable insert for anon role"
on "public"."user_infos"
as permissive
for insert
to public
with check (false);



